### ISSUE TITLE
[node-lucene] Could not create class org.apache.lucene.store.FSDirectory

### ISSUE THREAD

**Issue by maticrivo** [cancerberoSgx/node-lucene#20]
Hey, great library!
I'm trying to read an index directory but im getting the following error:
```
Could not create class org.apache.lucene.store.FSDirectory
java.lang.NoClassDefFoundError: org/apache/lucene/store/FSDirectory
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.store.FSDirectory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```

this is a snippet from my code:
```javascript
import path from 'path'
import * as lucene from 'node-lucene'
import * as java from 'node-java-rt'

try {
  const absolutePathToIndexFolder = path.join(__dirname, 'index-dir')
  const indexFolder = java.nio.file.Paths.getSync(absolutePathToIndexFolder)
  const directory = lucene.store.FSDirectory.open(indexFolder)
  const searcher = new lucene.search.IndexSearcher(directory)
} catch (err) {
  console.log(err)
}
```
the above code throws at the `const directory = ....` line

I have the `lucene-lib/lucene-core-7.7.2.jar` file

Any idea what am I missing?

Thanks.

**Comment by maticrivo** [comment]
i was missing the initialize command..
i added
```javascript
lucene.initialize()
```
and now it works.

Thanks for this library!
