### ISSUE TITLE
Error: Could not find method "doc

### ISSUE THREAD

**Issue by rak-dev** [cancerberoSgx/node-lucene#52]
Hello,
After successfully installing and integrating the node-Lucene with firestore. I ran into the following issue 

```
Initializing Query Parser
(node:11267) UnhandledPromiseRejectionWarning: Error: Could not find method "doc(org.apache.lucene.search.ScoreDoc)" on class "class org.apache.lucene.search.IndexSearcher". Possible matches:
  public org.apache.lucene.document.Document org.apache.lucene.search.IndexSearcher.doc(int,java.util.Set) throws java.io.IOException
  public org.apache.lucene.document.Document org.apache.lucene.search.IndexSearcher.doc(int) throws java.io.IOException
  public void org.apache.lucene.search.IndexSearcher.doc(int,org.apache.lucene.index.StoredFieldVisitor) throws java.io.IOException
at IndexSearcher.doc (/usr/host_app/node_modules/node-lucene/dist/src/search/IndexSearcher.js:49:52)
    at /usr/host_app/test.js:47:18
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:11267) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11267) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

- Node Version: v11.10.0
- JDK: OpenJDK version "1.8.0_312"
- Docker Ubuntu 
Please help following is my package.json dependencies list
```dependencies: {  
    "@firebase/app-compat": "^0.1.28",  
    "@google-cloud/connect-firestore": "^2.0.2",  
    "@google-cloud/firestore": "^4.15.1",  
    "body-parser": "^1.15.0",  
    "connect-mongo": "^4.6.0",  
    "cookie-parser": "^1.4.5",  
    "debug": "^2.2.0",  
    "dotenv": "^10.0.0",  
    "encoding": "^0.1.13",  
    "express": "^4.18.1",  
    "express-session": "^1.17.3",  
    "express-useragent": "^1.0.15",  
    "firebase-admin": "^9.11.0",  
    "fireorm": "^0.23.3",  
    "java": "^0.12.2",  
    "log4js": "^6.3.0",  
    "mongoose": "^6.0.5",  
    "mongoose-fire": "0.0.1",  
    "morgan": "^1.7.0",  
    "node-java-rt": "0.0.5",  
    "node-lucene": "^0.0.7",  
    "pug": "^3.0.2",  
    "reflect-metadata": "^0.1.13",  
    "serve-favicon": "^2.3.0"  }
```

This is a snippet from my code where it's throwing an error:`
```node
var topDocs = searcher.search(parser.parse('alexander'), 10);
        // logger.info("TopDocs=>", topDocs.scoreDocs)
        searcher.doc(topDocs.scoreDocs[0]).then(function (foundDoc) {
            try {
               
                logger.info(`Found "${foundDoc.get('title')}"  ${foundDoc.get('subtitle')}`);
                 } catch (error) {
                logger.error("Error In Searcher", error)
            }
        });;
```
I also tried with following way
```node
topDocs = searcher.search(parser.parse('alexander'), 10) 
const foundDoc = searcher.doc(topDocs.scoreDocs[0].doc)
console.log(`Found "${foundDoc.get('title')}" authored by ${foundDoc.get('author')}`);
```

But same issue

**Comment by rak-dev** [comment]
finally, after 2 days of struggle, I figure out the issue. It was related to a missing jar file. We need to copy Apache Lucene jar files in node-lucene lib folder manually.
